### ISSUE TITLE
Spurious versioning.

### ISSUE THREAD

**Issue by DBMoUK** [puppet-community/puppet-windows_firewall#25]
Latest Version downloaded from Puppet Forge has file name:

liamjbennett-windows_firewall-999.999.999.tar.gz

**Comment by liamjbennett** [comment]
This is not an issue with the module. Version 999.999.999 was released under the previous namespace to make it's depreciation clear. 

The latest version of the module can be found here: https://forge.puppetlabs.com/puppet/windows_firewall
